### PR TITLE
Add the ability to create a new file from within the file manager.

### PR DESCRIPTION
**Pull request by jrruethe**
My second attempt. 

This adds the ability to create a new file directly on the device from the browser.

### CODE REVIEW

**Comment by jrruethe** [comment]
Let me know if any other changes are required. Thanks!

**Comment by abarisani** [comment]
Thanks, I'll take a look as soon as I've the chance and merge it. There are some slight changes that I will do to mask errors that might leak the absolute path on the target filesystem but I can do so after the merge, along with an overall review of similar issues elsewhere in the code.

**Comment by abarisani** [comment]
Your pull request was merged, I had to add some fixes (https://github.com/inversepath/interlock/commit/5b82d4e0b409e61199410b7fd1a82a847285d8fd) to prevent unwanted behavior and max absolute paths (which we try to as much as we can), also we gofmt all of our code ;)

Thanks for the added feature!

**Comment by danbia** [comment]
@jrruethe, I've removed the submit action when pressing 'Enter' in order to allow to insert newline(s) when editing a new file: [https://github.com/inversepath/interlock/commit/ff9b7d9bedc56b948fa597fa4402b9f232bb5798](https://github.com/inversepath/interlock/commit/ff9b7d9bedc56b948fa597fa4402b9f232bb5798)

**Comment by jrruethe** [comment]
Thank you!

**Pull request merged**
