### PR TITLE
Add new file

### PR DESCRIPTION
**Pull request by jrruethe**
Hello! This is my very first pull request, so I apologize in advance if I am doing something wrong.

I made a modification to the Interlock application to allow a new file to be created directly on the device. It adds a button next to "New Directory" that opens a text editing dialog, where text can be typed or pasted. I find this much easier than needing to open Notepad on the host machine, save the file, and upload it, especially if the contents of the file are sensitive (I prefer not having a temporary file touch the hard drive of the host if it can be avoided).

It works well for me, so I thought I would share. If it can't/shouldn't be brought in, no hard feelings.

On a related note, I made a Docker image for building and running Interlock on my development machine, it might be useful: https://github.com/jrruethe/interlock-dev
Thanks for making such a cool application!

### CODE REVIEW

**Comment by abarisani** [comment]
@danbia could you check the UI side changes?

**Comment by danbia** [comment]
@abarisani the UI side changes look fine

**Comment by jrruethe** [comment]
Sorry about that! I didn't mean to have some of this as part of the pull request. I'm still learning Git and Github. I'll fix the requested changes. Do I just make another commit to the branch and it appears here?

**Comment by danbia** [comment]
@jrruethe, could you please prepare a clean branch which contains only the relevant commit(s) (without the portions you reverted in the latest fix commit) and the correspondent new pull request?

**Comment by jrruethe** [comment]
Closing this, and opening #25 instead for a cleaner merge. Thanks again!

**Comment by danbia** [comment]
@jrruethe, I've removed the submit action when pressing 'Enter' in order to allow to insert newline(s) when editing a new file: [https://github.com/inversepath/interlock/commit/ff9b7d9bedc56b948fa597fa4402b9f232bb5798](https://github.com/inversepath/interlock/commit/ff9b7d9bedc56b948fa597fa4402b9f232bb5798)

**Pull request closed without merging**
